# Generated by Django 5.2.1 on 2025-06-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_rename_first_name_customuser_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone',
        ),
    ]
